- hosts: all
  tasks:
  - name: Copy deployment file to  master
    copy:
      src: "{{ workspace }}/k8s/deploy-1-tagged.yml"
      dest: /home/ubuntu/deploy-1-tagged.yml
  - name: Copy deployment file to  master
    copy:
      src: "{{ workspace }}/k8s/service-1.yml"
      dest: /home/ubuntu/service-1.yml
  
  - name: delete old secret
    shell: "kubectl --kubeconfig=/home/ubuntu/.kube/config delete secret --ignore-not-found {{ secret_name }}"
  
  - name: get login credentials for ecr
    shell: "kubectl --kubeconfig=/home/ubuntu/.kube/config create secret docker-registry {{ secret_name }} --docker-server=https://{{ account }}.dkr.ecr.{{ aws_region }}.amazonaws.com --docker-username={{ account }} --docker-password={{ token }} --docker-email=kocagoz@gmail.com"

  - name: deploy the app k8s
    shell: "kubectl --kubeconfig=/home/ubuntu/.kube/config apply -f ."
    register: output

  - debug: msg="{{ output.stdout }}"