apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deploy
spec:
  replicas: 3 
  selector:  
    matchLabels:
      app: todo-app
  minReadySeconds: 10 
  strategy:
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1 
  template: 
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-pod
        image: "${IMAGE_TAG}"
        ports:
        - containerPort: 3000
      imagePullSecrets: 935026556399-ecr-registry