apiVersion: v1
kind: Service   
metadata:
  name: todo-app-svc
  labels:
    app: todo-flask
spec:
  type: LoadBalancer 
  ports:
  - name: htttp  
    port: 80        
    targetPort: 3000
  selector:
    app: todo-app
