apiVersion: v1
kind: Service   
metadata:
  name: todo-app-svc
  labels:
    app: todo-flask
spec:
  type: NodePort 
  ports:
  - nodePort: 30336  
    port: 80        
    targetPort: 3000
  selector:
    app: todo-app
